# Generated by Django 5.2.14 on 2026-05-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_deleted'], name='facilities_is_dele_2db4a7_idx'),
        ),
    ]
