# Generated by Django 5.2.14 on 2026-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_facility_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='baseline_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reduction_target',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='target_year',
            field=models.IntegerField(default=2035),
        ),
    ]
