# Generated by Django 5.2.14 on 2026-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_baseline_year_tenant_reduction_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='emissions_standard',
            field=models.CharField(default='epa_2025', max_length=100),
        ),
    ]
