# Generated by Django 5.2.14 on 2026-05-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='rawrecord',
            name='data_source',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.datasource'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant'], name='data_source_tenant__6e7360_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['source_type'], name='data_source_source__b1a60c_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['status'], name='data_source_status_1e5c21_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['uploaded_at'], name='data_source_uploade_78d0c4_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['parse_status'], name='raw_records_parse_s_9ab595_idx'),
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['data_source'], name='raw_records_data_so_e836cc_idx'),
        ),
    ]
