# Generated by Django 5.2.14 on 2026-05-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_datasource_tenant_alter_rawrecord_data_source_and_more'),
        ('tenants', '0003_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='tenants.facility'),
        ),
    ]
