# Generated by Django 5.2.14 on 2026-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_datasource_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
