# Generated by Django 5.2.14 on 2026-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_datasource_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
