# Generated by Django 5.2.14 on 2026-05-24 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=50)),
                ('activity_type', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND_TRANSPORT', 'Ground Transport'), ('PROCUREMENT', 'Procurement')], max_length=100)),
                ('activity_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=100)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('emission_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'emission_records',
            },
        ),
    ]
