# Generated by Django 5.2.14 on 2026-05-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['review_status'], name='emission_re_review__1c3d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['scope'], name='emission_re_scope_64eda0_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_type'], name='emission_re_activit_da897e_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['anomaly_flag'], name='emission_re_anomaly_8d79ab_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emission_re_activit_afed01_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant'], name='emission_re_tenant__7605bb_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='emission_re_tenant__f7d98d_idx'),
        ),
    ]
