# Generated by Django 5.2.14 on 2026-05-27 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_emissionrecord_tenant_and_more'),
        ('tenants', '0003_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='tenants.facility'),
        ),
    ]
