# Generated by Django 5.2.14 on 2026-05-24 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='emissions.emissionrecord')),
            ],
            options={
                'db_table': 'review_comments',
            },
        ),
    ]
