# Generated by Django 5.2.14 on 2026-05-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='emission_record',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['emission_record'], name='audit_logs_emissio_dfa305_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
    ]
